import type {
  ActivityRecord,
  AttentionItem,
  BulkReturnDetection,
  CheckoutItem,
  HomeStat,
  InventoryItem,
  InventoryStatus,
  OfflineState,
  RecoveryState,
  ReviewCandidate,
  StatusMeta,
  StoreLocation,
} from './types'

export const officialChallengeFacts = {
  itemTypes: 109,
  categories: 5,
  activeStorageLocations: 4,
} as const

export const inventory: InventoryItem[] = [
  {
    id: 'arduino-uno',
    name: 'Arduino Uno',
    code: 'ELC-0421',
    category: 'Electronics',
    kind: 'reusable',
    available: 9,
    checkedOut: 4,
    damaged: 1,
    location: 'Store 1 — Electronics',
    rack: 'Rack B3',
    imageUrl: null,
    lastSeen: '2 minutes ago',
    status: 'available',
    distribution: [
      { store: 'Store 1', qty: 6 },
      { store: 'Store 2', qty: 2 },
      { store: 'Store 4', qty: 1 },
    ],
    users: [
      { name: 'Team Robotics', qty: 3 },
      { name: 'Aisha R.', qty: 1 },
    ],
  },
  {
    id: 'ultrasonic-sensor',
    name: 'Ultrasonic Sensor',
    code: 'SNS-1180',
    category: 'Sensors',
    kind: 'reusable',
    available: 14,
    checkedOut: 6,
    damaged: 0,
    location: 'Store 1 — Sensors',
    rack: 'Rack A1',
    imageUrl: null,
    lastSeen: '11 minutes ago',
    status: 'available',
    distribution: [
      { store: 'Store 1', qty: 9 },
      { store: 'Store 3', qty: 5 },
    ],
    users: [{ name: 'Team Robotics', qty: 6 }],
  },
  {
    id: 'ir-sensor',
    name: 'IR Sensor',
    code: 'SNS-1204',
    category: 'Sensors',
    kind: 'reusable',
    available: 3,
    checkedOut: 8,
    damaged: 2,
    location: 'Store 2 — Sensors',
    rack: 'Rack A2',
    imageUrl: null,
    lastSeen: '1 hour ago',
    status: 'attention',
    distribution: [
      { store: 'Store 2', qty: 3 },
    ],
    users: [
      { name: 'Team Prototyping', qty: 5 },
      { name: 'Daniel K.', qty: 3 },
    ],
  },
  {
    id: 'screwdriver',
    name: 'Precision Screwdriver',
    code: 'TL-0092',
    category: 'Tools',
    kind: 'reusable',
    available: 22,
    checkedOut: 3,
    damaged: 0,
    location: 'Store 1 — Tools',
    rack: 'Rack C5',
    imageUrl: null,
    lastSeen: '5 minutes ago',
    status: 'available',
    distribution: [
      { store: 'Store 1', qty: 12 },
      { store: 'Store 2', qty: 6 },
      { store: 'Store 4', qty: 4 },
    ],
    users: [{ name: 'Maintenance', qty: 3 }],
  },
  {
    id: 'jumper-wires',
    name: 'Jumper Wires (40pc)',
    code: 'CBL-3310',
    category: 'Cables',
    kind: 'consumable',
    available: 48,
    checkedOut: 0,
    damaged: 0,
    location: 'Store 1 — Cables',
    rack: 'Rack D2',
    imageUrl: null,
    lastSeen: '20 minutes ago',
    status: 'available',
    distribution: [
      { store: 'Store 1', qty: 30 },
      { store: 'Store 3', qty: 18 },
    ],
    users: [],
  },
  {
    id: 'breadboard',
    name: 'Breadboard 830pt',
    code: 'ELC-0510',
    category: 'Electronics',
    kind: 'reusable',
    available: 0,
    checkedOut: 16,
    damaged: 1,
    location: 'Store 3 — Electronics',
    rack: 'Rack B1',
    imageUrl: null,
    lastSeen: '3 hours ago',
    status: 'attention',
    distribution: [{ store: 'Store 3', qty: 0 }],
    users: [{ name: 'Team Robotics', qty: 10 }, { name: 'Team Prototyping', qty: 6 }],
  },
  {
    id: 'soldering-iron',
    name: 'Soldering Iron',
    code: 'TL-0145',
    category: 'Workshop',
    kind: 'reusable',
    available: 5,
    checkedOut: 2,
    damaged: 0,
    location: 'Store 2 — Tools',
    rack: 'Rack C1',
    imageUrl: null,
    lastSeen: '40 minutes ago',
    status: 'checked-out',
    distribution: [
      { store: 'Store 2', qty: 5 },
    ],
    users: [{ name: 'Maintenance', qty: 2 }],
  },
  {
    id: 'multimeter',
    name: 'Digital Multimeter',
    code: 'TL-0201',
    category: 'Tools',
    kind: 'reusable',
    available: 7,
    checkedOut: 1,
    damaged: 0,
    location: 'Store 1 — Tools',
    rack: 'Rack C6',
    imageUrl: null,
    lastSeen: '9 minutes ago',
    status: 'available',
    distribution: [
      { store: 'Store 1', qty: 4 },
      { store: 'Store 4', qty: 3 },
    ],
    users: [{ name: 'Aisha R.', qty: 1 }],
  },
]

export const statusMeta: Record<
  InventoryStatus,
  StatusMeta
> = {
  available: { label: 'Available', tone: 'success' },
  'checked-out': { label: 'Checked Out', tone: 'cyan' },
  attention: { label: 'Need Attention', tone: 'warning' },
}

export const homeStats: HomeStat[] = [
  { label: 'Item Types', value: officialChallengeFacts.itemTypes, tone: 'cyan' },
  { label: 'Checked Out', value: 41, tone: 'violet' as const },
  { label: 'Need Attention', value: 3, tone: 'warning' as const },
  { label: 'Offline Stores', value: 1, tone: 'danger' as const },
]

export const needsAttention: AttentionItem[] = [
  {
    id: 'a1',
    title: '1 return needs review',
    detail: 'Bulk return · Store 1 · uncertain item',
    action: 'Review',
    href: '/scan?flow=bulk-return&stage=review',
    tone: 'warning',
  },
  {
    id: 'a2',
    title: '2 items overdue',
    detail: 'IR Sensor, Breadboard · Team Prototyping',
    action: 'View Items',
    href: '/inventory?filter=attention',
    tone: 'danger',
  },
  {
    id: 'a3',
    title: 'Store 3 offline',
    detail: 'Last sync 3 hours ago · 4 changes waiting',
    action: 'Check Status',
    href: '/system',
    tone: 'warning',
  },
]

export const activityStatusMeta: Record<ActivityRecord['status'], StatusMeta> = {
  synced: { label: 'Synced', tone: 'success' },
  offline: { label: 'Saved Offline', tone: 'warning' },
  review: { label: 'Review Needed', tone: 'warning' },
}

export const activities: ActivityRecord[] = [
  {
    id: 't-1042',
    type: 'return',
    title: 'Bulk Return · 7 items',
    time: 'Today · 14:32',
    store: 'Store 1',
    user: 'Team Robotics',
    qty: 7,
    status: 'synced',
    syncStatus: 'up-to-date',
    transactionId: 'TXN-2048-1042',
    items: [
      { name: 'Arduino Uno', qty: 3 },
      { name: 'Ultrasonic Sensor', qty: 3 },
      { name: 'Precision Screwdriver', qty: 1 },
    ],
    aiSummary: 'Six items were ready. One item was reviewed before confirmation.',
    online: true,
  },
  {
    id: 't-1041',
    type: 'check-out',
    title: 'Check-out · 2 items',
    time: 'Today · 13:05',
    store: 'Store 2',
    user: 'Aisha R.',
    qty: 2,
    status: 'synced',
    syncStatus: 'up-to-date',
    transactionId: 'TXN-2048-1041',
    items: [
      { name: 'Digital Multimeter', qty: 1 },
      { name: 'Precision Screwdriver', qty: 1 },
    ],
    aiSummary: 'Items matched by code scan. Assigned to Aisha R.',
    online: true,
  },
  {
    id: 't-1040',
    type: 'issue',
    title: 'Reported Damage · IR Sensor',
    time: 'Today · 11:48',
    store: 'Store 2',
    user: 'Daniel K.',
    qty: 2,
    status: 'review',
    syncStatus: 'online',
    transactionId: 'TXN-2048-1040',
    items: [{ name: 'IR Sensor', qty: 2 }],
    aiSummary: 'Damage report flagged for supervisor review.',
    online: true,
  },
  {
    id: 't-1039',
    type: 'return',
    title: 'Bulk Return · 4 items',
    time: 'Today · 10:20',
    store: 'Store 3',
    user: 'Team Prototyping',
    qty: 4,
    status: 'offline',
    syncStatus: 'saved-offline',
    transactionId: 'TXN-2048-1039',
    items: [
      { name: 'Breadboard 830pt', qty: 2 },
      { name: 'Jumper Wires (40pc)', qty: 2 },
    ],
    aiSummary: 'Saved offline while Store 3 was disconnected. Will sync when back online.',
    online: false,
  },
  {
    id: 't-1038',
    type: 'check-out',
    title: 'Check-out · 6 items',
    time: 'Yesterday · 16:11',
    store: 'Store 1',
    user: 'Team Robotics',
    qty: 6,
    status: 'synced',
    syncStatus: 'up-to-date',
    transactionId: 'TXN-2047-1038',
    items: [
      { name: 'Ultrasonic Sensor', qty: 4 },
      { name: 'Arduino Uno', qty: 2 },
    ],
    aiSummary: 'Batch check-out assigned to Team Robotics.',
    online: true,
  },
]

export const stores: StoreLocation[] = [
  { id: 'store-1', name: 'Store 1', area: 'Main Lab', status: 'online', lastSync: 'Just now', items: 512 },
  { id: 'store-2', name: 'Store 2', area: 'Workshop', status: 'online', lastSync: '2 min ago', items: 344 },
  { id: 'store-3', name: 'Store 3', area: 'Annex', status: 'offline', lastSync: '3 hours ago', items: 210 },
  { id: 'store-4', name: 'Store 4', area: 'Storage', status: 'online', lastSync: '5 min ago', items: 168 },
]

export const teams = [
  'Team Robotics',
  'Team Prototyping',
  'Maintenance',
  'Aisha R.',
  'Daniel K.',
]

export const checkoutScanCatalog: CheckoutItem[] = [
  { itemName: 'Arduino Uno', itemCode: 'ELC-0421', confidence: 98 },
  { itemName: 'Ultrasonic Sensor', itemCode: 'SNS-1180', confidence: 95 },
  { itemName: 'Precision Screwdriver', itemCode: 'TL-0092', confidence: 92 },
]

// Items surfaced during the bulk-return scan demo
export const bulkReturnDetections: BulkReturnDetection[] = [
  {
    id: 's1',
    itemName: 'Arduino Uno',
    itemCode: 'ELC-0421',
    quantity: 3,
    confidence: 96,
    status: 'ready',
    top: '15%',
    left: '8%',
    width: '31%',
    height: '25%',
  },
  {
    id: 's2',
    itemName: 'Ultrasonic Sensor',
    itemCode: 'SNS-1180',
    quantity: 2,
    confidence: 91,
    status: 'ready',
    top: '23%',
    left: '56%',
    width: '31%',
    height: '31%',
    labelSide: 'right',
  },
  {
    id: 's3',
    itemName: 'Precision Screwdriver',
    itemCode: 'TL-0092',
    quantity: 1,
    confidence: 95,
    status: 'ready',
    top: '58%',
    left: '14%',
    width: '27%',
    height: '27%',
  },
  {
    id: 's4',
    itemName: 'Ultrasonic Sensor',
    itemCode: 'SNS-1180',
    quantity: 1,
    confidence: 54,
    status: 'review',
    top: '57%',
    left: '58%',
    width: '28%',
    height: '29%',
    labelSide: 'right',
  },
]

export const bulkReturnReviewCandidates: ReviewCandidate[] = [
  { id: 'ultrasonic', itemName: 'Ultrasonic Sensor', itemCode: 'SNS-1180', confidence: 54 },
  { id: 'ir', itemName: 'IR Sensor', itemCode: 'SNS-1204', confidence: 39 },
]

export const bulkReturnStockBefore: Record<string, number> = {
  'Arduino Uno': 9,
  'Ultrasonic Sensor': 14,
  'Precision Screwdriver': 22,
  'IR Sensor': 3,
}

export const offlineStates: OfflineState[] = [
  {
    label: 'Online',
    message: 'Everything is Up to Date.',
    status: 'online',
    tone: 'success',
  },
  {
    label: 'Offline Mode',
    message: 'You can continue working. Changes will sync later.',
    status: 'offline',
    tone: 'warning',
  },
  {
    label: 'Saved Offline',
    message: 'This change is saved on this device.',
    status: 'saved-offline',
    tone: 'warning',
  },
  {
    label: 'Syncing',
    message: 'Updating store records now.',
    status: 'syncing',
    tone: 'cyan',
  },
  {
    label: 'Connection Restored',
    message: 'Your saved changes are syncing.',
    status: 'restored',
    tone: 'success',
  },
  {
    label: 'Everything is Up to Date',
    message: 'All stores are current.',
    status: 'up-to-date',
    tone: 'success',
  },
]

export const recoveryStates: RecoveryState[] = [
  {
    title: 'Camera Not Available',
    message: 'We could not open the camera on this device.',
    inventoryChanged: false,
    actions: ['Try Again', 'Choose Item Manually'],
    tone: 'warning',
  },
  {
    title: 'We Could Not Identify the Item',
    message: 'No inventory changes were made.',
    inventoryChanged: false,
    actions: ['Try Again', 'Choose Item Manually'],
    tone: 'warning',
  },
  {
    title: 'Detection Failed',
    message: 'The scan stopped before ORBIT could confirm the items.',
    inventoryChanged: false,
    actions: ['Scan Again'],
    tone: 'danger',
  },
  {
    title: 'No Inventory Found',
    message: 'Try a different search or clear your filters.',
    inventoryChanged: false,
    actions: ['Clear Search'],
    tone: 'cyan',
  },
  {
    title: 'Sync Failed',
    message: 'Your changes are saved offline and will sync later.',
    inventoryChanged: false,
    actions: ['Try Again'],
    tone: 'danger',
  },
  {
    title: 'Unknown Item',
    message: 'No inventory changes were made.',
    inventoryChanged: false,
    actions: ['Choose Item Manually', 'Scan Again'],
    tone: 'warning',
  },
]
